FROM php:8.3.30-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
    git unzip libzip-dev zlib1g-dev libicu-dev libpq-dev \
  && docker-php-ext-install pdo pdo_mysql pdo_pgsql zip intl opcache \
  && pecl install xdebug \
  && docker-php-ext-enable xdebug \
  && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2.9.7 /usr/bin/composer /usr/bin/composer
COPY docker/php/php.ini /usr/local/etc/php/conf.d/99-app.ini
COPY docker/php/xdebug.ini /usr/local/etc/php/conf.d/98-xdebug.ini

# Create non-root user
RUN useradd -u 1000 -m appuser \
  && mkdir -p /var/www/app \
  && chown -R appuser:appuser /var/www/app

WORKDIR /var/www/app

USER appuser

EXPOSE 9000
