parameters:
    app.user_registered_notification_log_path: '%kernel.project_dir%/var/notifications/user_registered.log'

services:
    App\User\Infrastructure\Notification\FileUserNotificationSenderService:
        arguments:
            $filePath: '%app.user_registered_notification_log_path%'

doctrine:
    orm:
        mappings:
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain/User'
                prefix: 'App\User\Domain\User'
                alias: User
            OtpChallenge:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain/OtpChallenge'
                prefix: 'App\User\Domain\OtpChallenge'
                alias: OtpChallenge
